{
  pkgs,
  lib,
  ...
}:
let
  cc-clip = pkgs.buildGoModule rec {
    pname = "cc-clip";
    version = "0.5.0";
    src = pkgs.fetchFromGitHub {
      owner = "ShunmeiCho";
      repo = "cc-clip";
      rev = "v${version}";
      hash = "sha256-V76TPQRBb5vMTDT+qz0VuP/SM85NFUQK1Zkmqw18s3Y=";
    };
    vendorHash = "sha256-luUizMtmwOBFuyuwDS7qmx7byotkg/ajOgtBbgOvnTk=";
    subPackages = [ "cmd/cc-clip" ];
    doCheck = false;
    meta = {
      description = "Paste images & receive notifications across SSH for Claude Code / Codex CLI";
      homepage = "https://github.com/ShunmeiCho/cc-clip";
      license = lib.licenses.mit;
      mainProgram = "cc-clip";
    };
  };

  # internal/shim/template.go の xclipShimTemplate を Nix で再現したもの。
  # cc-clip 本体の install サブコマンドが ~/.local/bin に動的生成するスクリプトを、
  # 起動時生成ではなくビルド時生成として home.file 経由で配置する。
  # port=18339, real xclip のフォールバック先は pkgs.xclip を使う。
  xclipShim = pkgs.writeShellScript "cc-clip-xclip-shim" ''
    # cc-clip xclip shim - intercepts Claude Code clipboard calls
    # Generated by Nix from cc-clip's internal/shim/template.go
    set -euo pipefail

    CC_CLIP_PORT="''${CC_CLIP_PORT:-18339}"
    CC_CLIP_ADDR="127.0.0.1:''${CC_CLIP_PORT}"
    CC_CLIP_TOKEN_FILE="''${CC_CLIP_TOKEN_FILE:-''${HOME}/.cache/cc-clip/session.token}"
    CC_CLIP_SESSION_FILE="''${CC_CLIP_SESSION_FILE:-''${HOME}/.cache/cc-clip/session.id}"
    CC_CLIP_PROBE_TIMEOUT_MS="''${CC_CLIP_PROBE_TIMEOUT_MS:-500}"
    CC_CLIP_FETCH_TIMEOUT_MS="''${CC_CLIP_FETCH_TIMEOUT_MS:-5000}"
    CC_CLIP_TOTAL_TIMEOUT_MS="''${CC_CLIP_TOTAL_TIMEOUT_MS:-8000}"
    REAL_XCLIP="${pkgs.xclip}/bin/xclip"

    _cc_clip_log() {
        if [ "''${CC_CLIP_DEBUG:-}" = "1" ]; then
            echo "cc-clip-shim: $*" >&2
        fi
    }

    _cc_clip_fallback() {
        _cc_clip_log "falling back to real xclip: $REAL_XCLIP $*"
        exec "$REAL_XCLIP" "$@"
    }

    _cc_clip_read_token() {
        if [ ! -f "$CC_CLIP_TOKEN_FILE" ]; then
            return 1
        fi
        cat "$CC_CLIP_TOKEN_FILE"
    }

    _cc_clip_session_header() {
        if [ -f "$CC_CLIP_SESSION_FILE" ]; then
            echo "X-CC-Clip-Session: $(cat "$CC_CLIP_SESSION_FILE" 2>/dev/null)"
        fi
    }

    _cc_clip_probe() {
        local timeout_s
        timeout_s=$(awk "BEGIN {printf \"%f\", ''${CC_CLIP_PROBE_TIMEOUT_MS}/1000}")
        if command -v timeout >/dev/null 2>&1; then
            timeout "$timeout_s" bash -c "echo >/dev/tcp/''${CC_CLIP_ADDR%%:*}/''${CC_CLIP_ADDR##*:}" 2>/dev/null
        elif command -v nc >/dev/null 2>&1; then
            nc -z -w 1 "''${CC_CLIP_ADDR%%:*}" "''${CC_CLIP_ADDR##*:}" 2>/dev/null
        else
            bash -c "echo >/dev/tcp/''${CC_CLIP_ADDR%%:*}/''${CC_CLIP_ADDR##*:}" 2>/dev/null
        fi
    }

    _cc_clip_fetch_json() {
        local path="$1"
        local token
        token=$(_cc_clip_read_token) || return 12
        local timeout_s
        timeout_s=$(awk "BEGIN {printf \"%f\", ''${CC_CLIP_FETCH_TIMEOUT_MS}/1000}")
        local session_hdr
        session_hdr=$(_cc_clip_session_header)
        curl -sf --max-time "$timeout_s" \
            -H "Authorization: Bearer ''${token}" \
            -H "User-Agent: cc-clip/0.1" \
            ''${session_hdr:+-H "$session_hdr"} \
            "http://''${CC_CLIP_ADDR}''${path}"
    }

    _cc_clip_fetch_binary() {
        local path="$1"
        local token
        token=$(_cc_clip_read_token) || return 12
        local timeout_s
        timeout_s=$(awk "BEGIN {printf \"%f\", ''${CC_CLIP_FETCH_TIMEOUT_MS}/1000}")
        local session_hdr
        session_hdr=$(_cc_clip_session_header)
        local tmpfile
        tmpfile=$(mktemp 2>/dev/null) || return 20
        if curl -sf --max-time "$timeout_s" \
            -o "$tmpfile" \
            -H "Authorization: Bearer ''${token}" \
            -H "User-Agent: cc-clip/0.1" \
            ''${session_hdr:+-H "$session_hdr"} \
            "http://''${CC_CLIP_ADDR}''${path}"; then
            if [ ! -s "$tmpfile" ]; then
                _cc_clip_log "fetch returned empty body"
                rm -f "$tmpfile"
                return 10
            fi
            cat "$tmpfile"
            rm -f "$tmpfile"
            return 0
        else
            local rc=$?
            rm -f "$tmpfile"
            return $rc
        fi
    }

    ARGS="$*"

    case "$ARGS" in
        *"-selection clipboard"*"-t TARGETS"*"-o"*)
            _cc_clip_log "intercepting TARGETS check"
            if _cc_clip_probe; then
                RESULT=$(_cc_clip_fetch_json "/clipboard/type" 2>/dev/null) || {
                    _cc_clip_log "fetch type failed, exit=$?"
                    _cc_clip_fallback "$@"
                }
                TYPE=$(echo "$RESULT" | grep -o '"type":"[^"]*"' | head -1 | cut -d'"' -f4)
                if [ "$TYPE" = "image" ]; then
                    FORMAT=$(echo "$RESULT" | grep -o '"format":"[^"]*"' | head -1 | cut -d'"' -f4)
                    echo "image/''${FORMAT:-png}"
                    exit 0
                fi
                _cc_clip_fallback "$@"
            else
                _cc_clip_log "tunnel not reachable"
                _cc_clip_fallback "$@"
            fi
            ;;

        *"-selection clipboard"*"-t image/"*"-o"*)
            _cc_clip_log "intercepting image read"
            if _cc_clip_probe; then
                if _cc_clip_fetch_binary "/clipboard/image"; then
                    exit 0
                fi
                _cc_clip_log "fetch image failed, falling back"
                _cc_clip_fallback "$@"
            else
                _cc_clip_log "tunnel not reachable"
                _cc_clip_fallback "$@"
            fi
            ;;

        *)
            _cc_clip_fallback "$@"
            ;;
    esac
  '';
in
{
  home.packages = [ cc-clip ];

  home.file = lib.mkIf pkgs.stdenv.isLinux {
    ".local/bin/xclip" = {
      source = xclipShim;
      executable = true;
    };
  };

  home.sessionPath = lib.optionals pkgs.stdenv.isLinux [
    "$HOME/.local/bin"
  ];

  launchd.agents.cc-clip = lib.mkIf pkgs.stdenv.isDarwin {
    enable = true;
    config = {
      ProgramArguments = [
        "${cc-clip}/bin/cc-clip"
        "serve"
      ];
      RunAtLoad = true;
      KeepAlive = true;
      StandardOutPath = "/Users/aspulse/Library/Logs/cc-clip.out.log";
      StandardErrorPath = "/Users/aspulse/Library/Logs/cc-clip.err.log";
    };
  };
}
